### PR TITLE
add hesai 40p support

### LINKED ISSUE #42: Does it work with other lidar types?
I tried using another lidar device and updated the velodyne topic in `lidar_camera_calibration` https://github.com/ankitdhall/lidar_camera_calibration/blob/master/conf/lidar_camera_calibration.yaml#L4 . I am getting the following error: 
```
[ INFO] [1522777695.370229735]: First marker with ID: 10 detected
[ WARN] [1522777695.382916640]: TF to MSG: Quaternion Not Properly Normalized
[ INFO] [1522777695.432211706]: Velodyne scan received at 1.52278e+09
[ INFO] [1522777695.432235629]: marker_6dof received at 1.52278e+09
Failed to find match for field 'ring'.

Initial Rot 0.000796274    -0.999999 -0.000796274
           0  0.000796274           -1
           1  0.000796274  6.34053e-07
10=(1107.69,1012.23) (1024.24,1102.09) (935.85,1021.21) (1020.12,931.427) Txyz=0.111969 0.849601 2.85558 Rxyz=-0.620609 1.73495 -1.76494 
20=(1498.92,1023.35) (1407.57,1114.76) (1310.73,1023.5) (1400.71,932.817) Txyz=0.816052 0.817916 2.70597 Rxyz=-0.78969 1.8706 -1.74944 
10=(1107.74,1012.18) (1024.28,1102.05) (935.82,1021.17) (1020.11,931.481) Txyz=0.111959 0.849404 2.85501 Rxyz=-0.620971 1.73789 -1.76304 
20=(1498.92,1023.39) (1407.6,1114.73) (1310.82,1023.57) (1400.71,932.755) Txyz=0.816282 0.818081 2.70652 Rxyz=-0.78935 1.86932 -1.7504 
[find_transform-2] process has died [pid 18752, exit code -11, cmd /.../devel/lib/lidar_camera_calibration/find_transform __name:=find_transform __log:=/cyngn_log/9a3596ec-3763-11e8-bf5e-1c1b0d9bb6f8/find_transform-2.log].
log file: /log/9a3596ec-3763-11e8-bf5e-1c1b0d9bb6f8/find_transform-2*.log
``` 

I am able to calibrate when using a Velodyne lidar. The only difference that I made to cause this error is use a different lidar and different topic name. Both use PointCloud2.msg.

### PR DESCRIPTION
**Pull request by ruichen-v**
1. Add parser for /pandar_points provided by [Hesai Lidar Driver](https://github.com/HesaiTechnology/HesaiLidar-ros).
2. Add option in `config_file.txt` to select between Velodyne lidar and Hesai lidar
3. Updated README.md. Add a note about fixing synchronization between Hesai lidar driver and aruco mapping node.

Fixes #42  #48

### CODE REVIEW

**Comment by ankitdhall** [comment]
@ruichen-v thanks for creating the feature to make this work with LiDARs from Hesai. Can you resolve the conflicts so I can merge it?

**Comment by ankitdhall** [comment]
There is a change in the master (from another pull request) that allows for initializing the translation vector (in addition to the already existing initialization of the rotations).

**Comment by GaHooooo** [comment]
Hi , I try the code you post  https://github.com/ruichen-v/lidar_camera_calibration , but  only Mono8 window visible , Cloud and polygon doesn't work
图片

**Comment by ruichen-v** [comment]
Hi, please make sure the following changes are made:

1. In `lidar_camera_calibration.yaml`, adapt camera/lidar topic name to your actual setting.
2. In `find_transform.launch`, change aruco mapping params.
3. Change HesaiLidar-ros code according to README.

Hope it helps.

**Comment by GaHooooo** [comment]
> Hi, please make sure the following changes are made:
> 
>     1. In `lidar_camera_calibration.yaml`, adapt camera/lidar topic name to your actual setting.
> 
>     2. In `find_transform.launch`, change aruco mapping params.
> 
>     3. Change HesaiLidar-ros code according to README.
> 
> 
> Hope it helps.
Thank you for your prompt reply
emmmmmmmmm,I am sure i make change as you say 
there are my changed  file 
[find_transform.launch.tar.gz](https://github.com/ankitdhall/lidar_camera_calibration/files/3586359/find_transform.launch.tar.gz)
[config_file.txt.tar.gz](https://github.com/ankitdhall/lidar_camera_calibration/files/3586360/config_file.txt.tar.gz)
[lidar_camera_calibration.yaml.tar.gz](https://github.com/ankitdhall/lidar_camera_calibration/files/3586361/lidar_camera_calibration.yaml.tar.gz)
[zed_left_uurmi.ini.tar.gz](https://github.com/ankitdhall/lidar_camera_calibration/files/3586367/zed_left_uurmi.ini.tar.gz)
图片
bagfile:  https://pan.baidu.com/s/1FUPetfqbG4cJAtqxzFMEDA 
keyword: 4yt7

hope your reply

**Comment by GaHooooo** [comment]
> Hi, please make sure the following changes are made:
> 
>     1. In `lidar_camera_calibration.yaml`, adapt camera/lidar topic name to your actual setting.
> 
>     2. In `find_transform.launch`, change aruco mapping params.
> 
>     3. Change HesaiLidar-ros code according to README.
> 
> 
> Hope it helps.

it works！！！！Thank you ！！！！

**Pull request merged**
